[package]
name = "rust-stream-player"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.12", features = ["stream"] }
tokio = { version = "1", features = ["full"] }
ffmpeg-next = "7.1.0"
sdl2 = "0.36"
pixels = "0.13"
winit = "0.29"
log = "0.4"
env_logger = "0.10"